server:
  ip: localhost
  port: 9090

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///job_sys?serverTimezone=GMT%2b8
    username: root
    password: 123456
#  redis:
#    host: 127.0.0.1
#    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #????mybatis?xml??

files:
  upload:
    path: C:/Users/73541/Desktop/project/client/files/